[package]
name = "hll"
version = "0.1.0"
authors = ["Thomas E <slashdevsda@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fasthash = "0.4.0"